openapi: 3.2.0
info:
  title: Labguru Recipes API
  description: 'Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.


    Join our dedicated Slack channel

    to be in direct contact with our API team and be informed about the latest updates.


    ***API introduction and overview***'
  version: v1
tags:
- name: Recipes
paths:
  /api/v1/recipes/{id}:
    delete:
      summary: Delete recipe
      tags:
      - Recipes
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: recipe id
        schema:
          type: integer
      responses:
        '204':
          description: no content
        '404':
          description: not found
      operationId: deleteApiV1RecipesById
      x-operation-id-source: derived
