openapi: 3.0.0
info:
  title: Labguru Antibodies Instrument usages API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Instrument usages
paths:
  /api/v1/samples/{sample_id}/instrument_usages/{id}:
    delete:
      summary: Delete instrument usage
      tags:
      - Instrument usages
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: sample_id
        in: path
        required: true
        description: sample id
        schema:
          type: integer
      - name: id
        in: path
        required: true
        description: instrument usage id
        schema:
          type: integer
      responses:
        '204':
          description: no content
        '404':
          description: not found
